version: "3.9"
services:
        proxy:
                image: unclemakson/proxy_v2:latest
                build:
                        context: https://github.com/NerodaMaksim/proxy_v2.git->main
                        network: host
                volumes:
                      - type: bind
                        source: ./config.json
                        target: /app/config.json
                      - type: bind
                        source: .
                        target: /app/files
                network_mode: host
